### ISSUE TITLE
Long project names truncated

### ISSUE THREAD

**Issue by StephenKing** [shellscape/OctoGerrit#1]
Hi Andrew,

thanks for OctoGerrit! I gave it a try for https://review.typo3.org and it looked like that:

![screen shot 2016-03-13 at 12 44 58](https://cloud.githubusercontent.com/assets/277561/13756516/84238f5e-ea20-11e5-821a-97613301ae61.png)

What people mostly disturbed was:
- project names cropped in list of reviews (we have pretty long ones)
- centered fixed-size table

Maybe a combined fox for both - enlarging the table and giving the project name more space - would make people happier.

**Comment by shellscape** [comment]
Thanks for the kind words. Please feel free to edit the css on your end for your needs. If you'd like 100% width table, you can find an example of how to accomplish that with the side-by-side diff css. You could also shorten the issue name/title column and expand the project name column. 

We personally like the 990x max width as it's much cleaner and hides information we don't find to be essential. So while we won't be making the requested change to the css here in this repo, it's certainly possible to do so on your own copy.
